In [22]:
import pandas as pd
import numpy as ny

In [23]:
data1_df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")
data2_df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv")
data3_df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv")

In [24]:
data1_df.shape

(4008, 11)

In [25]:
data2_df.shape

(996, 11)

In [26]:
data3_df.shape

(7070, 11)

In [30]:
for df in [data1_df, data2_df, data3_df]:
    df.columns = df.columns.str.lower()

In [41]:
data1_df = data1_df.rename(columns={"st":"state"})

In [45]:
data1_df.columns

Index(['customer', 'state', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'total claim amount', 'policy type', 'vehicle class'],
      dtype='object')

In [47]:
data2_df = data2_df.rename(columns={"st":"state"})

In [48]:
data2_df.columns

Index(['customer', 'state', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'total claim amount', 'policy type', 'vehicle class'],
      dtype='object')

In [39]:
data3_df.columns

Index(['customer', 'state', 'customer lifetime value', 'education', 'gender',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'total claim amount', 'vehicle class'],
      dtype='object')

In [49]:
for df in [data1_df, data2_df, data3_df]:
    df.columns = df.columns.str.strip().str.replace(" ", "_")

In [54]:
combined_df = pd.concat([data1_df, data2_df,data3_df],axis=0, ignore_index=True)
combined_df

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount,policy_type,vehicle_class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.600000,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.200000,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.600000,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.200000,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.200000,Corporate Auto,Two-Door Car
...,...,...,...,...,...,...,...,...,...,...,...
9057,LA72316,California,M,Bachelor,23405.98798,71941,73,0,198.234764,Personal Auto,Four-Door Car
9058,PK87824,California,F,College,3096.511217,21604,79,0,379.200000,Corporate Auto,Four-Door Car
9059,TD14365,California,M,Bachelor,8163.890428,0,85,3,790.784983,Corporate Auto,Four-Door Car
9060,UP19263,California,M,College,7524.442436,21941,96,0,691.200000,Personal Auto,Four-Door Car
9061,Y167826,California,M,College,2611.836866,0,77,0,369.600000,Corporate Auto,Two-Door Car

In [55]:
combined_df.shape

(9062, 11)

In [56]:
duplicates = combined_df.duplicated().sum()

In [57]:
duplicates

np.int64(996)

In [58]:
combined_df = combined_df.drop_duplicates().reset_index(drop=True)

In [59]:
combined_df.duplicated().sum()

np.int64(0)

In [62]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv")
df.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

In [63]:
df.shape

(10910, 27)

In [64]:
df.columns.unique()

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type', 'month'],
      dtype='object')

In [65]:
pivot1 = df.pivot_table(
    index='sales_channel', 
    values='total_claim_amount',
    aggfunc='sum'
).round(2)

In [67]:
pivot1

               total_claim_amount
sales_channel
Agent                  1810226.82
Branch                 1301204.00
Call Center             926600.82
Web                     706600.04

In [68]:
pivot2 = df.pivot_table(
    index='gender', 
    columns='education', 
    values='customer_lifetime_value', 
    aggfunc='mean'
).round(2)

In [69]:
pivot2

education  Bachelor  College   Doctor  High School or Below   Master
gender
F           7874.27  7748.82  7328.51               8675.22  8157.05
M           7703.60  8052.46  7415.33               8149.69  8168.83