In [1]:
import pandas as pd

In [2]:
url = " https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"

In [3]:
insurance_df = pd.read_csv(url)

In [4]:
insurance_df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [5]:
insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [6]:
insurance_df.shape

(4008, 11)

In [7]:
insurance_df.nunique()

Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64

In [8]:
insurance_df.describe()

             Income  Monthly Premium Auto  Total Claim Amount
count   1071.000000           1071.000000         1071.000000
mean   39295.701214            193.234360          404.986909
std    30469.427060           1601.190369          293.027260
min        0.000000             61.000000            0.382107
25%    14072.000000             68.000000          202.157702
50%    36234.000000             83.000000          354.729129
75%    64631.000000            109.500000          532.800000
max    99960.000000          35354.000000         2893.239678

In [9]:
insurance_df.describe(include="object")

,Customer,ST,GENDER,Education,Customer Lifetime Value,Number of Open Complaints,Policy Type,Vehicle Class
count,1071,1071,954,1071,1068,1071,1071,1071
unique,1071,8,5,6,1027,6,3,6
top,RB50392,Oregon,F,Bachelor,445811.34%,1/0/00,Personal Auto,Four-Door Car
freq,1,320,457,324,4,830,780,576

In [16]:
location_counts = insurance_df["ST"].value_counts()

In [17]:
less_common_locations = location_counts.sort_values(ascending=True).head()

In [18]:
less_common_locations

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

In [19]:
policy_counts = insurance_df["Policy Type"].value_counts()

In [20]:
top_policy = policy_counts.max()

In [21]:
policy_counts

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [22]:
top_policy

780

In [23]:
personal_df = insurance_df.loc[insurance_df['Policy Type'] == 'Personal Auto']
corporate_df = insurance_df.loc[insurance_df['Policy Type'] == 'Corporate Auto']

In [24]:
avg_income_personal = personal_df['Income'].mean()
avg_income_corporate = corporate_df['Income'].mean()

In [27]:
avg_income_corporate

np.float64(41390.31196581197)

In [28]:
avg_income_personal

np.float64(38180.69871794872)